######################################################################
# Automatically generated by qmake (3.0) Mon Sep 1 18:22:42 2014
######################################################################

TEMPLATE = app
TARGET = example
INCLUDEPATH += . ../lib
QT += multimedia
CONFIG += c++11

# Input
SOURCES += main.cpp

LIBS += -L../lib -lQtMixer
