######################################################################
# Automatically generated by qmake (3.0) Mon Sep 1 18:22:42 2014
######################################################################

TEMPLATE = app
TARGET = example
INCLUDEPATH += . ../lib
QT += multimedia widgets
CONFIG += c++11

# Input
SOURCES += main.cpp \
    MainWindow.cpp \
    SampleListEntry.cpp

LIBS += -L../lib -lQtMixer

HEADERS += \
    MainWindow.h \
    SampleListEntry.h
